### ISSUE TITLE
Location of notebook `example_notebooks/load_data.ipynb`

### ISSUE THREAD

**Issue by glukhove** [ignotur/Random-forest-open-cluster#12]
Should it be in folder data/download_data_scripts ?

**Comment by Catarina-Alves** [comment]
I think not. When you arrive at the repo you usually start by exploring the examples, so an example of loading the data should be there. The scripts are what you will use when doing things "for real". At that point, if you want an example, you can go again to the examples but you might not need them anymore.

I can try to make a symbolic link between these two locations (so the same notebook is on both), if you think it is useful.

**Comment by glukhove** [comment]
Probably, you are right. I faced this problem when found a place with saving plots and npy's. If we move this notebook to data folder, path for saving looks less ugly.
But I think we can create nice variable with path to data folder.

**Comment by Catarina-Alves** [comment]
I will try to make an absolute path and in that way it is less ugly.

**Comment by glukhove** [comment]
Wait a sec. I'll upload my version.

**Comment by rtarun** [comment]
I changed the following line in example_notebooks/random_forest.ipynb

true_clusters_2d_hist_file = f'true_clusters_2d_hist_{number_clusters}.npy'
true_clusters_2d_hist = np.load(true_clusters_2d_hist_file, allow_pickle=True)

to:

true_clusters_2d_hist_dir  = os.path.realpath(
    os.path.join(os.path.dirname(os.getcwd()), os.path.dirname('data/')))

true_clusters_2d_hist_file = true_clusters_2d_hist_dir+'/'+f'true_clusters_2d_hist_{number_clusters}.npy'
true_clusters_2d_hist = np.load(true_clusters_2d_hist_file, allow_pickle=True)

and it worked!

**Comment by glukhove** [comment]
I believe I fixed the issue here: https://github.com/ignotur/Random-forest-open-cluster/pull/14
